name: Build, Publish & Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Login to Azure Container Registry
      - name: Docker Login
        uses: azure/docker-login@v2
        with:
          login-server: propacr.azurecr.io
          username: propacr
          password: ${{ secrets.ACR_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        id: docker-build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            propacr.azurecr.io/tiles:latest
            propacr.azurecr.io/tiles:${{ github.sha }}
          build-args: |
            GITHUB_USERNAME=brenwell
          secrets: |
            github_token=${{ secrets.GH_PAT_TOKEN }}

      # Read deployment JSON
      - name: Deployment JSON
        id: read-json
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const file = fs.readFileSync('./deployment.json', 'utf8');
            const data = JSON.parse(file);
            data.image.tag = "${{ github.sha }}"
            return { manifest: JSON.stringify(data) }

      # Trigger  deployment
      - name: Deployment
        id: deployment
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: Deployment
          repo: sh-proptech/deployment
          token: ${{ secrets.GH_PAT_TOKEN }}
          inputs: ${{ steps.read-json.outputs.result }}
          ref: main
