name: Run
run-name: "Run 'tegola cache seed ${{ github.event.inputs.args }}'"

on:
  workflow_dispatch: # This makes the workflow run manually
    inputs:
      maxZoom:
        description: "Maximum zoom level"
        required: true
        default: "9"
      minZoom:
        description: "Minimum zoom level"
        required: true
        default: "5"


jobs:
  cache-seed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read JSON file
        id: read-json
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const file = fs.readFileSync('job.json', 'utf8');
            const data = JSON.parse(file); 
            const maxZoom = ${{ github.event.inputs.maxZoom }};
            const minZoom = ${{ github.event.inputs.minZoom }};
            data.args = ['cache','seed'].concat([
              `--max-zoom=${maxZoom}`,
              `--min-zoom=${minZoom}`
            ])
            console.log(data);
            return { manifest: JSON.stringify(data) }

      - name: Dispatch deployment
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: Deployment
          repo: sh-proptech/deployment
          token: ${{ secrets.GH_PAT_TOKEN }}
          inputs: ${{ steps.read-json.outputs.result }}
